name: Build Lambda Layers
on: [push]

jobs:
  build:
    name: Build Lambda Layers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Lambda Layers
        run: make layers
