name: Build Lambda Layers
on: [push]

jobs:
  build:
    name: Build Lambda Layers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Lambda Layers
        run: make layers
      - name: Remove .gitignore before packing artifacts
        run: rm -rf export/.gitignore
      - name: Publish artifacts
        uses: actions/upload-artifact@v1
        with:
          name: layers
          path: export

  publish:
    name: Publish Lambda Layers
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: layers
          path: export
      - name: Publish Layers
        uses: ./.github/actions/aws-publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Update config.json
        uses: github-actions-x/commit@v2.5
        with:
          files: config.json
          name: GitHub Actions
          email: noreply@github.com
          message: Published newest layer versions
