name: Build Lambda Layers
on: [push]

jobs:
  build:
    name: Build Lambda Layers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Lambda Layers
        run: make layers
      - name: Publish 7.4 artifact
        uses: actions/upload-artifact@v1
        with:
          name: php-lambda-imagick-7.4.zip
          path: export/layer-php-imagick-74.zip
      - name: Publish 7.3 artifact
        uses: actions/upload-artifact@v1
        with:
          name: php-lambda-imagick-7.3.zip
          path: export/layer-php-imagick-73.zip
      - name: Publish 7.2 artifact
        uses: actions/upload-artifact@v1
        with:
          name: php-lambda-imagick-7.2.zip
          path: export/layer-php-imagick-72.zip
